package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	private java.lang.String lastName;

	public TestBO() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public TestBO(java.lang.String name, java.lang.String lastName) {
		this.name = name;
		this.lastName = lastName;
	}

}