package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestBO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TestBO() {
    }




}